language: python
python:
    - "3.5"
before_script:
    - pip install coverage && pip install python-coveralls
install: "pip install . && pip install git+git://github.com/bnbalsamo/pypairtree.git"
services:
    - mongodb
script: coverage run --source archstor tests.py
after_success:
    - coveralls
